//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace CarInsurance.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class InsuranceEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new InsuranceEntities object using the connection string found in the 'InsuranceEntities' section of the application configuration file.
        /// </summary>
        public InsuranceEntities() : base("name=InsuranceEntities", "InsuranceEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new InsuranceEntities object.
        /// </summary>
        public InsuranceEntities(string connectionString) : base(connectionString, "InsuranceEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new InsuranceEntities object.
        /// </summary>
        public InsuranceEntities(EntityConnection connection) : base(connection, "InsuranceEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Insuree> Insurees
        {
            get
            {
                if ((_Insurees == null))
                {
                    _Insurees = base.CreateObjectSet<Insuree>("Insurees");
                }
                return _Insurees;
            }
        }
        private ObjectSet<Insuree> _Insurees;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Insurees EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToInsurees(Insuree insuree)
        {
            base.AddObject("Insurees", insuree);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InsuranceModel", Name="Insuree")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Insuree : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Insuree object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="firstName">Initial value of the FirstName property.</param>
        /// <param name="lastName">Initial value of the LastName property.</param>
        /// <param name="emailAddress">Initial value of the EmailAddress property.</param>
        /// <param name="dateOfBirth">Initial value of the DateOfBirth property.</param>
        /// <param name="carYear">Initial value of the CarYear property.</param>
        /// <param name="carMake">Initial value of the CarMake property.</param>
        /// <param name="carModel">Initial value of the CarModel property.</param>
        /// <param name="dUI">Initial value of the DUI property.</param>
        /// <param name="speedingTickets">Initial value of the SpeedingTickets property.</param>
        /// <param name="coverageType">Initial value of the CoverageType property.</param>
        /// <param name="quote">Initial value of the Quote property.</param>
        public static Insuree CreateInsuree(global::System.Int32 id, global::System.String firstName, global::System.String lastName, global::System.String emailAddress, global::System.DateTime dateOfBirth, global::System.Int32 carYear, global::System.String carMake, global::System.String carModel, global::System.Boolean dUI, global::System.Int32 speedingTickets, global::System.Boolean coverageType, global::System.Decimal quote)
        {
            Insuree insuree = new Insuree();
            insuree.Id = id;
            insuree.FirstName = firstName;
            insuree.LastName = lastName;
            insuree.EmailAddress = emailAddress;
            insuree.DateOfBirth = dateOfBirth;
            insuree.CarYear = carYear;
            insuree.CarMake = carMake;
            insuree.CarModel = carModel;
            insuree.DUI = dUI;
            insuree.SpeedingTickets = speedingTickets;
            insuree.CoverageType = coverageType;
            insuree.Quote = quote;
            return insuree;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, false, "FirstName");
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, false, "LastName");
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EmailAddress
        {
            get
            {
                return _EmailAddress;
            }
            set
            {
                OnEmailAddressChanging(value);
                ReportPropertyChanging("EmailAddress");
                _EmailAddress = StructuralObject.SetValidValue(value, false, "EmailAddress");
                ReportPropertyChanged("EmailAddress");
                OnEmailAddressChanged();
            }
        }
        private global::System.String _EmailAddress;
        partial void OnEmailAddressChanging(global::System.String value);
        partial void OnEmailAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateOfBirth
        {
            get
            {
                return _DateOfBirth;
            }
            set
            {
                OnDateOfBirthChanging(value);
                ReportPropertyChanging("DateOfBirth");
                _DateOfBirth = StructuralObject.SetValidValue(value, "DateOfBirth");
                ReportPropertyChanged("DateOfBirth");
                OnDateOfBirthChanged();
            }
        }
        private global::System.DateTime _DateOfBirth;
        partial void OnDateOfBirthChanging(global::System.DateTime value);
        partial void OnDateOfBirthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CarYear
        {
            get
            {
                return _CarYear;
            }
            set
            {
                OnCarYearChanging(value);
                ReportPropertyChanging("CarYear");
                _CarYear = StructuralObject.SetValidValue(value, "CarYear");
                ReportPropertyChanged("CarYear");
                OnCarYearChanged();
            }
        }
        private global::System.Int32 _CarYear;
        partial void OnCarYearChanging(global::System.Int32 value);
        partial void OnCarYearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CarMake
        {
            get
            {
                return _CarMake;
            }
            set
            {
                OnCarMakeChanging(value);
                ReportPropertyChanging("CarMake");
                _CarMake = StructuralObject.SetValidValue(value, false, "CarMake");
                ReportPropertyChanged("CarMake");
                OnCarMakeChanged();
            }
        }
        private global::System.String _CarMake;
        partial void OnCarMakeChanging(global::System.String value);
        partial void OnCarMakeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CarModel
        {
            get
            {
                return _CarModel;
            }
            set
            {
                OnCarModelChanging(value);
                ReportPropertyChanging("CarModel");
                _CarModel = StructuralObject.SetValidValue(value, false, "CarModel");
                ReportPropertyChanged("CarModel");
                OnCarModelChanged();
            }
        }
        private global::System.String _CarModel;
        partial void OnCarModelChanging(global::System.String value);
        partial void OnCarModelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean DUI
        {
            get
            {
                return _DUI;
            }
            set
            {
                OnDUIChanging(value);
                ReportPropertyChanging("DUI");
                _DUI = StructuralObject.SetValidValue(value, "DUI");
                ReportPropertyChanged("DUI");
                OnDUIChanged();
            }
        }
        private global::System.Boolean _DUI;
        partial void OnDUIChanging(global::System.Boolean value);
        partial void OnDUIChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SpeedingTickets
        {
            get
            {
                return _SpeedingTickets;
            }
            set
            {
                OnSpeedingTicketsChanging(value);
                ReportPropertyChanging("SpeedingTickets");
                _SpeedingTickets = StructuralObject.SetValidValue(value, "SpeedingTickets");
                ReportPropertyChanged("SpeedingTickets");
                OnSpeedingTicketsChanged();
            }
        }
        private global::System.Int32 _SpeedingTickets;
        partial void OnSpeedingTicketsChanging(global::System.Int32 value);
        partial void OnSpeedingTicketsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean CoverageType
        {
            get
            {
                return _CoverageType;
            }
            set
            {
                OnCoverageTypeChanging(value);
                ReportPropertyChanging("CoverageType");
                _CoverageType = StructuralObject.SetValidValue(value, "CoverageType");
                ReportPropertyChanged("CoverageType");
                OnCoverageTypeChanged();
            }
        }
        private global::System.Boolean _CoverageType;
        partial void OnCoverageTypeChanging(global::System.Boolean value);
        partial void OnCoverageTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Quote
        {
            get
            {
                return _Quote;
            }
            set
            {
                OnQuoteChanging(value);
                ReportPropertyChanging("Quote");
                _Quote = StructuralObject.SetValidValue(value, "Quote");
                ReportPropertyChanged("Quote");
                OnQuoteChanged();
            }
        }
        private global::System.Decimal _Quote;
        partial void OnQuoteChanging(global::System.Decimal value);
        partial void OnQuoteChanged();

        #endregion

    }

    #endregion

}
